### PR TITLE
I have made better response words

### PR DESCRIPTION
**Pull request by Svenpaj**
Look at my new code!

### CODE REVIEW

**Review by ironboy — DISMISSED** [review]
I like the changes but you forgot to update the endpoint-tests they now fail!

**Comment by Svenpaj** [comment]
I have fixed the failing tests in the endpoint-test

**Review by ironboy — COMMENTED** [review]
Great! Now the tests work as well. let's keep it like this!

**Review by ironboy — APPROVED** [review]
Approved!

**Pull request merged**
